
#################################################################################
#                                                                               #
#                                                                               #
#  |            ------------   --        |     ------------    -------------|   #
#  |        /        |        |  \       |    |            |   |                #
#  |       /         |        |   \      |    |                |                #
#  |      /          |        |    \     |    |     --------   |                #
#  |-----|           |        |     \    |    |     |      |   -------------|   #
#  |      \          |        |      \   |    |     ---|   |                |   #
#  |       \         |        |       \  |    |            |                |   #
#  |        \   ------------  |        --     -------------|   |-------------   #
#                                                                               #
#                                                                               #
#                            # Made By Whagwan                       #
#                                                                               #
#                                                                               #
#################################################################################
spawn_area:
  x: 220
  y: 65
  z: 73
  point1:
    x: 201
    y: 64
    z: 92
  point2:
    x: 239
    y: 84
    z: 54