#################################################################################
#                                                                               #
#                                                                               #
#  |            ------------   --        |     ------------    -------------|   #
#  |        /        |        |  \       |    |            |   |                #
#  |       /         |        |   \      |    |                |                #
#  |      /          |        |    \     |    |     --------   |                #
#  |-----|           |        |     \    |    |     |      |   -------------|   #
#  |      \          |        |      \   |    |     ---|   |                |   #
#  |       \         |        |       \  |    |            |                |   #
#  |        \   ------------  |        --     -------------|   |-------------   #
#                                                                               #
#                                                                               #
#                            # Made By Whagwan                        #
#                                                                               #
#                                                                               #
#################################################################################

name: Kings
description: Kings Minigame.
main: minigame.kings.Main
version: 1.2
commands:
  kings:
    description: Command.
    aliases: [ks]